  
image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 6080
    onOpen: ignore 
  
tasks:
  - init:    pip3 install --upgrade pip                                             &&
             apachectl start
